#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    sum = 0
    count = 0
    for ch in s:
        if ch=='U':
            sum=sum+1
            if sum==0:
                count=count+1
        else:
            sum=sum-1
    return count         

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
